### ISSUE TITLE
Allow empty prescriptions

### ISSUE THREAD

**Issue by o-farag** [Lenscrafters-Capstone/LensCrafters-free#19]
Users might only have on eye that needs correction. In this case we should allow an empty prescription which could generate plano or blanked lenses.

**Comment by EsteBran** [comment]
Opticore allows for plano lenses, given this comment on their readme:

> Creates an optical lens with two flat, spherical or apsheric surfaces. Set surface radius = 0 for a flat surface.

I will make the change when I get time.
